dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master
  - develop
  - deepesh/geth_version_update
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
node_js:
  - "8"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE payment_development;'
  - sudo apt-get update 
  - sudo apt-get install nodejs 
  - sudo apt-get install npm  
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
  - sudo apt-get install ethereum
  - sudo apt-get install solc
  - geth version
install: 
  - npm install 
before_script:  
  - nohup sh tools/runTestRpc.sh </dev/null >/dev/null 2>&1 &
  - bash contracts/compile.sh
script:  
  - truffle test  
  - cd mocha_test/scripts/  
  - bash travis_test.sh  
after_script:
  - kill $(ps aux | grep 'testrpc' | awk '{print $2}')
  - kill $(ps aux | grep 'geth' | awk '{print $2}')
